path:
    input: ../../data/input
    processed: ../../data/processed/
    result: ../../data/result/
    figure: ../../data/figure/

hydrophobic:
  - A
  - F
  - C
  - L
  - I
  - W
  - V
  - M
  - Y
polar:
  - K
  - R
  - H
  - D
  - T
  - E
  - N
  - Q
