# change {root} with the root of your directory

path:
    root: /
    src: /
    model: /model/
    data: /data/
    # the directory where the full pdbs are saved
    protein: /data/preprocess/unprocessed/
    # the directory where the pdbs without heteroatoms are saved
    hetatm: /data/preprocess/hetatm
    # the directory where the pdbs without water molecules are saved
    hoh: /data/preprocess/hoh/
    #the directory where the chains are saved
    chain: /data/preprocess/processed/

log: True
hydrophobic:
  - A
  - F
  - C
  - L
  - I
  - W
  - V
  - M
  - Y
polar:
  - K
  - R
  - H
  - D
  - T
  - E
  - N
  - Q
