version: '3'

services:
  molpatch_plot:
    build: .
    volumes:
      - ./data/input:/data/input
      - ./data/processed:/data/processed
      - ./data/result:/data/result
      - ./data/figure:/data/figure